import os
import sys
import copy
import tomllib

BASE = 0x1f340 # 🍀

# Get the Varation Selectors id for a glyph id
def get_selectors(id):
    def var_sel(i):
        assert(i < 256)
        # https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)
        if i < 16:
            return 0xFE00 + i
        i -= 16
        # https://en.wikipedia.org/wiki/Variation_Selectors_Supplement
        return 0xE0100 + i
    return [
        var_sel((id >> 8) & 0xFF),
        var_sel(id & 0xFF),
    ]

def main():
    with open("config.toml", "rb") as f:
        config = tomllib.load(f)
        # Fetch data from config
        icons = config.get("icons", {})

        # Table file
        table_lines = []
        table_lines.append("-- Generated by gen_table.py")
        table_lines.append("return {")

        id = 0
        for icon_name in sorted(icons.keys()):
            iconvars = icons[icon_name]
            table_lines.append(f"\t[\"{icon_name}\"] = {{")
            for icon_var, icon in iconvars.items():
                base_glyph = f"{icon_name}-{icon_var}"
                selectors = get_selectors(id)
                table_lines.append(f"\t\t[\"{icon_var}\"] = \"{chr(BASE)}{chr(selectors[0])}{chr(selectors[1])}\", -- colr-icons-{base_glyph} U+{BASE:x} U+{selectors[0]:x} U+{selectors[1]:x}")
                id += 1
            table_lines.append(f"\t}},")


        # Save table
        table_lines.append("}")
        table_lines.append("")
        with open("table.lua", "w", encoding="utf-8") as f:
            f.write("\n".join(table_lines))
        print("[gen_table.py] table.lua")

if __name__ == "__main__":
    main()
