import os
import sys
import copy
import tomllib

def main():
	with open("config.toml", "rb") as f:
		config = tomllib.load(f)
		# Fetch data from config
		icons = config.get("icons", {})

		# Table file
		table_lines = []
		table_lines.append("-- Generated by gen_table.py")
		table_lines.append("return {")


		codepoint = 0xF1F00
		for icon_name in sorted(icons.keys()):
			iconvars = icons[icon_name]
			table_lines.append(f"\t[\"{icon_name}\"] = {{")
			for icon_var, icon in iconvars.items():
				base_glyph = f"{icon_name}-{icon_var}"
				table_lines.append(f"\t\t[\"{icon_var}\"] = \"{chr(codepoint)}\", -- colr-icons-{base_glyph} U+{codepoint:x}")
				codepoint += 1
			table_lines.append(f"\t}},")


		# Save table
		table_lines.append("}")
		table_lines.append("")
		with open("table.lua", "w", encoding="utf-8") as f:
			f.write("\n".join(table_lines))
		print("[gen_table.py] table.lua")

if __name__ == "__main__":
	main()
